<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('PPSPTP ')?>

        <?php
        echo $this->headMeta()
                ->appendName('viewport', 'width=device-width, initial-scale=1.0')
                ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?php
        echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                ->prependStylesheet($this->basePath() . '/css/stylesheet.css')
                ->prependStylesheet($this->basePath() . '/css/responsive.css')
                ->prependStylesheet($this->basePath() . '/css/slider.min.css')
        ?>
        <?php
        echo $this->headScript()
                ->prependFile($this->basePath() . '/js/myscript.js', 'text/javascript', array('conditional' => 'lt IE 9',))
                ->prependFile($this->basePath() . '/js/slider.min.js', 'text/javascript', array('conditional' => 'lt IE 9',))
        ;
        ?>

        <!-- Scripts -->

    </head>
    <body>
              <nav>
            
            <div class="container">
                        <a href="<?php echo $this->url('home') ?>"><img class="logo" src="images/logo.png"/></a>
                <h4 class="reg_log"><a href="<?php echo $this->url('register') ?>"><?php echo $this->translate('REGISTER') ?></a>  |  <a href="<?php echo $this->url('login') ?>"><?php echo $this->translate('LOGIN') ?></a></h4>
                <div class="clear"/>
            </div>
                <div id="nav">
    <div id="nav_wrapper">
            <div class="container">
                <ul class="navigation">
                    <li><a href="<?php echo $this->url('home') ?>"><?php echo $this->translate('Home') ?></a></li>
                    <li><a href="<?php echo $this->url('about') ?>"><?php echo $this->translate('About') ?></a>
                        <ul>
                            <li class="active"><a href="<?php echo $this->url('howtoknow') ?>"><?php echo $this->translate('How to know') ?></a></li>
                            </li>
                            <li class="active"><a href="<?php echo $this->url('comingout') ?>"><?php echo $this->translate('Coming out') ?></a></li>
                            </li>
                            <li class="active"><a href="<?php echo $this->url('behappy') ?>"><?php echo $this->translate('Be happy') ?></a></li>
                            </li>
                            <li class="active"><a href="<?php echo $this->url('respect') ?>"><?php echo $this->translate('Respect') ?></a></li>
                            </li>
                           <li class="active"><a href="<?php echo $this->url('transition') ?>"><?php echo $this->translate('Transition') ?></a></li>
                            </li>
                            <li class="active"><a href="<?php echo $this->url('resources') ?>"><?php echo $this->translate('Resources') ?></a></li>
                            <li class="active"><a href="<?php echo $this->url('bootstrap') ?>"><?php echo $this->translate('Bootstrap') ?></a></li>
                        </ul>
                    </li>
                    
                    
                    </li>
                    
                    
                    <li class="active"><a href="<?php echo $this->url('service') ?>"><?php echo $this->translate('Services') ?></a></li>
                    <li class="active"><a href="<?php echo $this->url('members') ?>"><?php echo $this->translate('Members') ?></a></li>
                <li><a href="<?php echo $this->url('contact') ?>"><?php echo $this->translate('Contact') ?></a></li>
                </ul>
                <div class="clear"/>
            </div>
            </div></div>
        </nav>
        <header>
			<img class="banner" src="images/banner.jpg"/>
		</header>
		<section>
		<div class="container">
		<div class="left_happy">
			<p class="pink top_p">
				Your 'inferiority' as you may refer to it can also be seen as a unique or individual quality. 	
			</p>
			<p class="bottom_p">
				What makes you feel these things are 'inferior' to everyone else? If there is no norm amongst human beings, how can there possibly be any form of inferiority?
				Don't give the power of influencing your thoughts to people that don't care about you. Understand that most people aren't out there to judge you. Out of everyone you see, most don't care or know about how poorly you did on your last math test, or how you've gained a little weight since last summer.
			</p>
		</div>
		<div class="middle_happy">
			<p class="pink top_p">
				Nobody's perfect. They say the grass is always greener in someone else's yard. 	
			</p>
			<p class="middle_p">
				If there's always someone out there with more money than you, or prettier than you, realize there's always someone uglier than you. 
				There's someone with a bigger nose or heftier than you. There's someone with even smaller or larger breasts than you. You'll struggle with feeling content if you get caught up in constantly comparing yourself to others. 
			</p>
		</div>
		<div class="right_happy">
			<p class="pink top_p">
				Think about what it is you are really afraid of. 
			</p>
			<p class="rights_p">
				What is it you fear will happen, upon the revealing of your inferiority to everyone else?
				Do you fear people looking, or making comments? These are all valid worries but bear in mind - everyone is different. 
				Any comments you receive are invalid and must be ignored at all costs. It's absolutely certain there is something they think is wrong with them too. 
			</p>
		</div>
		<div class="clear"/>
		</div>
		</section>
		<section>
			<div class="container">
			<div class="col_left">

				<h3 class="blue">
					Seriously consider just what is so 'inferior'.
				</h3>
				<p>
					If you have a complex about a specific body part, such as your arms, legs, feet, or hands, think hard about what exactly makes them 'inferior' to everyone 
					else, and write this on paper if it helps. 
					Seriously think about the logic of these things. You're not going to 
					get stopped in the street for having what you think of as 'inferior' hands or feet. If you find your inferiority difficult to deal with, enlist 
					the help of a friend. Good friends will help you achieve your goals, whatever they may be. <br/><br/>
					For limbs it may be to eventually be able to walk around in shorts(for leg complexes). Good friends will tell you the truth, and you can work together on ways to make you feel better about yourself.
					If you find it difficult to talk with friends, ask them if they ever feel inferior, and you may be surprised how worried people get.
					See a counselor. 
					If you feel 'inferior', and cannot seriously enlist the help of a friend 
					for whatever reason, remember all of the above, and perhaps you can talk to a counselor if need be. If you have a close friend, they can also help you.
					If it helps, examine other people (not obvious staring.) <br/><br/>
					How do they react to their body? How do they show themselves?
					Do they have a similar body type to you? This could really help you reach your goals. 
					Respect yourself. Look in the mirror and give yourself compliments.
					If you don't respect yourself, who will? <br/><br/>
					To be really happy all the time is not only impossible but unrealistic, but you can make a conscious effort to be happy all the time. However, to be really happy you need to accept yourself for whom you are. Listen, nobody is perfect. Check this out - any time you enter a room full of people, I bet you get easily attracted to and
					(I am sure) a bit jealous of those you see laughing or smiling and making the rounds...don't you? 
					Truth be told, there is nothing special about them. They just forgot all about themselves and what people think about them. Be one of those people!
				</p>
			</div>
			<div class="col_right">
				<p>
					<span class="right_p">If</span> it helps, examine other people (not obvious staring.) How do they react to their body? How do they show themselves? Do they have a similar body type to you? This could really help you reach your goals. 
					Respect yourself. Look in the mirror and give yourself compliments. If you don't respect yourself, who will? 
					To be really happy all the time is not only impossible but unrealistic, but you can make a conscious effort to be happy all the time.<br/><br/>
					However, to be really happy you need to accept yourself for whom you are. Listen, nobody is perfect. Check this 
					out - any time you enter a room full of people, I bet you get easily attracted to and (I am sure) a bit jealous of those you see laughing or smiling and making the rounds...don't you? Truth be told, there is nothing special about them. They just forgot all about themselves and what people think about them. Be one of those people!
					Spend time thinking about your strengths (everyone has them) and you will find yourself more happy, and also more confident! 
					Lastly, don't concentrate too much on yourself. Get interested in others and you will see all your fears and worries which make you sad melt away. <br/><br/>
					Happiness is beautiful. A smile is much more beautiful than a frown. This may not be a real step, but don't ever frown! 
					Most people in the world can sometimes feel somewhat inferior to others. These things we tell ourselves, that we aren't good or pretty enough are in no way based on facts. On this page, we will go through simple steps on how people can overcome any feelings of inferiority that they may face.
				</p>
			</div>
					<div class="clear"/>
			</div>
		</section>
		<footer>
			<div class="container">
				<div class="col_footer_left">
					<h3>JOIN OUR NEWSLETTER</h3>
					<button><a class="white" href="<?php echo $this->url('register') ?>"><?php echo $this->translate('SIGN-UP FOR NEWLETTER') ?></a></button>
				</div>
				<div class="col_footer_middle">
					<h3 class="dt_num3">SERVICE TIMES</h3>
					<dl>
						<dt class="dt_num2">Sundays at 9:30 & 11:30AM</dt>
						<dd class="dt_num3">Human Rights Organisation</dd>
					</dl>
				</div>
				<div class="col_footer_right">
					<h3>CONNECT WITH US</h3>
						<div class="socail_media">
							<a target = "_blank"href="https://www.facebook.com/pages/Protea-Psychosocial-Project-for-Trans-People/1613032075611085?fref=ts"><img class="facebook" src='images/facebook.png' width='' height='' onmouseover="this.src='images/facebookhover.png';" onmouseout="this.src='images/facebook.png';" /></a>
							<a target = "_blank"href="https://twitter.com/ppsptp"><img class="twitter" src='images/twitter.png' width='' height='' onmouseover="this.src='images/twitterhover.png';" onmouseout="this.src='images/twitter.png';" /></a>
							<a target = "_blank" href="#"><img class="youtube" src='images/youtube.png' width='' height='' onmouseover="this.src='images/youtubehover.png';" onmouseout="this.src='images/youtube.png';" /></a>
							<a href="<?php echo $this->url('contact') ?>"><img class="email" src='images/email.png' width='' height='' onmouseover="this.src='images/emailhover.png';" onmouseout="this.src='images/email.png';" /></a>
						</div>
				</div>
				<div class="clear"/>
				</div>
				<hr class="hr"/><br/>
				<p class="copy">&copy; Copyright 2015. All Rights Reserved. Privacy Policy</p>
		</footer>
	<script src="http://code.jquery.com/jquery-2.1.0.min.js"></script>
	<script src="js/myscripts.js"></script>
	</body>
</html>