<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
            <?php echo $this->headTitle('PPSPTP ')?>

        <?php
        echo $this->headMeta()
                ->appendName('viewport', 'width=device-width, initial-scale=1.0')
                ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?php
        echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                ->prependStylesheet($this->basePath() . '/css/stylesheet.css')
                ->prependStylesheet($this->basePath() . '/css/responsive.css')
                ->prependStylesheet($this->basePath() . '/css/slider.min.css')
        ?>
        <?php
        echo $this->headScript()
                ->prependFile($this->basePath() . '/js/myscript.js', 'text/javascript', array('conditional' => 'lt IE 9',))
                ->prependFile($this->basePath() . '/js/slider.min.js', 'text/javascript', array('conditional' => 'lt IE 9',))
        ;
        ?>

        <!-- Scripts -->

    </head>
    <body>
              <nav>
            
            <div class="container">
                        <a href="<?php echo $this->url('home') ?>"><img class="logo" src="images/logo.png"/></a>
                <h4 class="reg_log"><a href="<?php echo $this->url('register') ?>"><?php echo $this->translate('REGISTER') ?></a>  |  <a href="<?php echo $this->url('login') ?>"><?php echo $this->translate('LOGIN') ?></a></h4>
                <div class="clear"/>
            </div>
                <div id="nav">
    <div id="nav_wrapper">
            <div class="container">
                <ul class="navigation">
                    <li><a href="<?php echo $this->url('home') ?>"><?php echo $this->translate('Home') ?></a></li>
                    <li><a href="<?php echo $this->url('about') ?>"><?php echo $this->translate('About') ?></a>
                        <ul>
                            <li class="active"><a href="<?php echo $this->url('howtoknow') ?>"><?php echo $this->translate('How to know') ?></a></li>
                            </li>
                            <li class="active"><a href="<?php echo $this->url('comingout') ?>"><?php echo $this->translate('Coming out') ?></a></li>
                            </li>
                            <li class="active"><a href="<?php echo $this->url('behappy') ?>"><?php echo $this->translate('Be happy') ?></a></li>
                            </li>
                            <li class="active"><a href="<?php echo $this->url('respect') ?>"><?php echo $this->translate('Respect') ?></a></li>
                            </li>
                           <li class="active"><a href="<?php echo $this->url('transition') ?>"><?php echo $this->translate('Transition') ?></a></li>
                            </li>
                            <li class="active"><a href="<?php echo $this->url('resources') ?>"><?php echo $this->translate('Resources') ?></a></li>
                            <li class="active"><a href="<?php echo $this->url('bootstrap') ?>"><?php echo $this->translate('Bootstrap') ?></a></li>
                        </ul>
                    </li>
                    
                    
                    </li>
                    
                    
                    <li class="active"><a href="<?php echo $this->url('service') ?>"><?php echo $this->translate('Services') ?></a></li>
                    <li class="active"><a href="<?php echo $this->url('members') ?>"><?php echo $this->translate('Members') ?></a></li>
                <li><a href="<?php echo $this->url('contact') ?>"><?php echo $this->translate('Contact') ?></a></li>
                </ul>
                <div class="clear"/>
            </div>
            </div></div>
        </nav>
        <header>
            <img class="banner" src="images/banner_shapes.jpg"/>
        </header>
        <section>
		<div class="container">
			<div class="service_left_col">
				<h3 class="blue"> OUR SERVICES</h3>
					<ul>
						<li>To offer an integrated psychosocial service treating traumatised trans* individuals, their significant others and promoting their rights</li> 
						<li>To create awareness of trans* people's needs</li> 
						<li>To provide for the educational and training needs and to empower all people involved in the care and management of trans* people and adolescents who have been traumatised as well as their families.</li> 
						<li>To provide a compassionate and holistic integrated medical and psychosocial service to survivors of rape, attempted rape and sexual abuse in adults, children and their families.</li> 
						<li>To provide an integrated psychosocial and support service to HIV/AIDS patients and their significant others. </li>
						<li>To create an environment and making facilities available to support these services and to promote the prevention of trauma. </li>
					</ul>
			</div>			
			<div class="service_right_col">
				<h3 class="blue">Head Office</h3>
					<p>1233 Calcrete Street</p>
					<p class="top_text">Lutzville, Western Cape, South Africa</p>
					<p><span class="blue">Fax:</span> +555 797 534 01</p>
					<p class="middle_text"><span class="blue">Tel:</span> 073 636 7470</p>
					<p><span class="blue">Email:</span> name@domain.com</p>
			</div>
			<div class="clear"/>
		</div>
		</section>
		<section>
		<div class="container">
				<img class="service_img_left" src="images/services_one.png"/>
				<img class="service_img_middle" src="images/services_two.png"/>
				<img class="service_img_right" src="images/services_three.png"/>
						<div class="clear";/>
		</div>
		</section>
		<footer>
			<div class="container">
				<div class="col_footer_left">
					<h3>JOIN OUR NEWSLETTER</h3>
					<button><a class="white" href="<?php echo $this->url('register') ?>"><?php echo $this->translate('SIGN-UP FOR NEWLETTER') ?></a></button>
				</div>
				<div class="col_footer_middle">
					<h3 class="dt_num3">SERVICE TIMES</h3>
					<dl>
						<dt class="dt_num2">Sundays at 9:30 & 11:30AM</dt>
						<dd class="dt_num3">LHuman Rights Organisation</dd>
					</dl>
				</div>
				<div class="col_footer_right">
					<h3>CONNECT WITH US</h3>
						<div class="socail_media">
							<a target = "_blank"href="https://www.facebook.com/pages/Protea-Psychosocial-Project-for-Trans-People/1613032075611085?fref=ts"><img class="facebook" src='images/facebook.png' width='' height='' onmouseover="this.src='images/facebookhover.png';" onmouseout="this.src='images/facebook.png';" /></a>
							<a target = "_blank"href="https://twitter.com/ppsptp"><img class="twitter" src='images/twitter.png' width='' height='' onmouseover="this.src='images/twitterhover.png';" onmouseout="this.src='images/twitter.png';" /></a>
							<a target = "_blank" href="#"><img class="youtube" src='images/youtube.png' width='' height='' onmouseover="this.src='images/youtubehover.png';" onmouseout="this.src='images/youtube.png';" /></a>
							<a href="<?php echo $this->url('contact') ?>"><img class="email" src='images/email.png' width='' height='' onmouseover="this.src='images/emailhover.png';" onmouseout="this.src='images/email.png';" /></a>
						</div>
				</div>
											<div class="clear"/>
				</div>
				<hr class="hr"/><br/>
				<p class="copy">&copy; Copyright 2015. All Rights Reserved. Privacy Policy</p>
		</footer>
	<script src="http://code.jquery.com/jquery-2.1.0.min.js"></script>
	<script src="js/myscripts.js"></script>
	</body>
</html>