<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('PPSPTP ')?>

        <?php
        echo $this->headMeta()
                ->appendName('viewport', 'width=device-width, initial-scale=1.0')
                ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?php
        echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                ->prependStylesheet($this->basePath() . '/css/stylesheet.css')
                ->prependStylesheet($this->basePath() . '/css/responsive.css')
                ->prependStylesheet($this->basePath() . '/css/slider.min.css')
        ?>
        <?php
        echo $this->headScript()
                ->prependFile($this->basePath() . '/js/myscript.js', 'text/javascript', array('conditional' => 'lt IE 9',))
                ->prependFile($this->basePath() . '/js/slider.min.js', 'text/javascript', array('conditional' => 'lt IE 9',))
        ;
        ?>

        <!-- Scripts -->

    </head>
    <body>
               <nav>
            
            <div class="container">
                        <a href="<?php echo $this->url('home') ?>"><img class="logo" src="images/logo.png"/></a>
                <h4 class="reg_log"><a href="<?php echo $this->url('register') ?>"><?php echo $this->translate('REGISTER') ?></a>  |  <a href="<?php echo $this->url('login') ?>"><?php echo $this->translate('LOGIN') ?></a></h4>
                <div class="clear"/>
            </div>
                <div id="nav">
    <div id="nav_wrapper">
            <div class="container">
                <ul class="navigation">
                    <li><a href="<?php echo $this->url('home') ?>"><?php echo $this->translate('Home') ?></a></li>
                    <li><a href="<?php echo $this->url('about') ?>"><?php echo $this->translate('About') ?></a>
                        <ul>
                            <li class="active"><a href="<?php echo $this->url('howtoknow') ?>"><?php echo $this->translate('How to know') ?></a></li>
                            </li>
                            <li class="active"><a href="<?php echo $this->url('comingout') ?>"><?php echo $this->translate('Coming out') ?></a></li>
                            </li>
                            <li class="active"><a href="<?php echo $this->url('behappy') ?>"><?php echo $this->translate('Be happy') ?></a></li>
                            </li>
                            <li class="active"><a href="<?php echo $this->url('respect') ?>"><?php echo $this->translate('Respect') ?></a></li>
                            </li>
                           <li class="active"><a href="<?php echo $this->url('transition') ?>"><?php echo $this->translate('Transition') ?></a></li>
                            </li>
                            <li class="active"><a href="<?php echo $this->url('resources') ?>"><?php echo $this->translate('Resources') ?></a></li>
                            <li class="active"><a href="<?php echo $this->url('bootstrap') ?>"><?php echo $this->translate('Bootstrap') ?></a></li>
                        </ul>
                    </li>
                    
                    
                    </li>
                    
                    
                    <li class="active"><a href="<?php echo $this->url('service') ?>"><?php echo $this->translate('Services') ?></a></li>
                    <li class="active"><a href="<?php echo $this->url('members') ?>"><?php echo $this->translate('Members') ?></a></li>
                <li><a href="<?php echo $this->url('contact') ?>"><?php echo $this->translate('Contact') ?></a></li>
                </ul>
                <div class="clear"/>
            </div>
            </div></div>
        </nav>
        <header>
			<img class="banner" src="images/banner_transition.jpg"/>
		</header>
		<section>
			<div class="container">
			<div class="col_left_co"><br/><br/>

				<h3 class="blue">
					Medical Necessity of Hormone Therapy 
				</h3>
				<p>
					Feminizing/masculinising hormone therapy – the administration of exogenous endocrine agents to induce feminizing or masculinising changes – is a medically necessary intervention for many transsexual, transgender, and gender nonconforming individuals with gender dysphoria (Newfield,Hart, Dibble, & Kohler, 2006; Pfafflin & Junge, 1998).  
					Some people seek maximum feminization/masculinisation, while others experience relief with an androgynous presentation resulting from hormonal minimization of existing secondary sex characteristics (Factor & Rothblum, 2008).
					Hormone therapy must be individualized based on a patient’s goals, the risk/benefit ratio of medications, the presence of other medical conditions, and consideration of social and economic issues. 
					Hormone therapy can provide significant comfort to patients who do not wish to make a social gender role transition or undergo surgery, or who are unable to do so (Meyer III, 2009).
					Hormone therapy is a recommended criterion for some, but not all, surgical treatments for gender dysphoria 
				</p>
				<h3 class="blue">
					Surgery
				</h3>
				<p>
					Sex Reassignment Surgery Is Effective and Medically Necessary
					Surgery – particularly genital surgery – is often the last and the most considered step in the treatment process for gender dysphoria .
					While many transsexual, transgender, and gender nonconforming individuals find comfort with their gender identity, role, and expression without surgery, for many others surgery is essential and medically necessary to alleviate their gender dysphoria (Hage& Karim, 2000). 
				</p><br/>
				<h3 class="blue">
					For the male-to-female (MtF) patient, surgical procedures may include the following: 
				</h3><br/>
				<ul>
					<li>Breast/chest surgery: augmentation mammoplasty (implants/lipofilling);</li>
					<li>Genital surgery: penectomy, orchidectomy, Labiaplasty, Vaginoplasty, clitoroplasty, vulvoplasty;</li>
					<li>Non-genital, non-breast surgical interventions: facial feminization surgery, liposuction, lipofilling, voice surgery, thyroid cartilage reduction, gluteal augmentation (implants/lipofilling), hair reconstruction, and various aesthetic procedures</li>
				</ul><br/><br/>
				<h3 class="blue">
					For the female-to-male (FtM) patient, surgical procedures may include the following:  
				</h3><br/>
				<ul>
					<li>Breast/chest surgery: subcutaneous mastectomy, creation of a male chest</li>
					<li>Genital surgery: hysterectomy/ovariectomy, reconstruction of the fixed part of the urethra, which can be combined with a metoidioplasty or with a phalloplasty (employing a pedicled or free vascularised flap), vaginectomy, scrotoplasty, and implantation of erection and/or testicular prostheses</li>
					<li>Non-genital, non-breast surgical interventions: voice surgery (rare), liposuction, lipofilling, pectoral implants, and various aesthetic procedures. </li>
				</ul><br/><br/>
				
			</div>
			<div class="col_right_co"><br/><br/>
				<h3 class="pink">Criteria for Hormone Therapy</h3><br/>
				<ul>
					<li>Persistent, well-documented gender dysphoria</li>
					<li>Capacity to make a fully informed decision and to consent for treatment;</li>
					<li>Age of majority in a given country (if younger, follow the Standards of Care outlined in section</li>
					<li>If significant medical or mental health concerns are present, they must be reasonably wellcontrolled </li>
				</ul><br/><br/>
				<h3 class="pink">Physical Effects of Hormone Therapy </h3><br/>
				<h4>In FtM patients, the following physical changes are expected to occur</h4>
				<br/>
				<ul>
					<li>Deepened voice, clitoral enlargement (variable), growth in facial and body hair, cessation of menses, atrophy of breast tissue, increased libido, and decreased percentage of body fat compared to muscle mass.</li>
					<li>Breast growth (variable), decreased libido and erections, decreased testicular size, and increased percentage of body fact compared to muscle mass.</li>
					<li>Most physical changes, whether feminizing or masculinising, occur over the course of two years. </li>
					<li>The amount of physical change and the exact timeline of effects can be highly variable. </li>
				</ul><br/><br/>
			</div>
					<div class="clear"/>
			</div>
		</section>
		<footer>
			<div class="container">
				<div class="col_footer_left">
					<h3>JOIN OUR NEWSLETTER</h3>
					<button>EMAIL SIGNUP</button>
				</div>
				<div class="col_footer_middle">
					<h3 class="dt_num3">SERVICE TIMES</h3>
					<dl>
						<dt class="dt_num2">Sundays at 9:30 & 11:30AM</dt>
						<dd class="dt_num3">Human Rights Organisation</dd>
					</dl>
				</div>
				<div class="col_footer_right">
					<h3>CONNECT WITH US</h3>
						<div class="socail_media">
							<a target = "_blank"href="https://www.facebook.com/pages/Protea-Psychosocial-Project-for-Trans-People/1613032075611085?fref=ts"><img class="facebook" src='images/facebook.png' width='' height='' onmouseover="this.src='images/facebookhover.png';" onmouseout="this.src='images/facebook.png';" /></a>
							<a target = "_blank"href="https://twitter.com/ppsptp"><img class="twitter" src='images/twitter.png' width='' height='' onmouseover="this.src='images/twitterhover.png';" onmouseout="this.src='images/twitter.png';" /></a>
							<a target = "_blank" href="#"><img class="youtube" src='images/youtube.png' width='' height='' onmouseover="this.src='images/youtubehover.png';" onmouseout="this.src='images/youtube.png';" /></a>
							<a href="<?php echo $this->url('contact') ?>"><img class="email" src='images/email.png' width='' height='' onmouseover="this.src='images/emailhover.png';" onmouseout="this.src='images/email.png';" /></a>
						</div>
				</div>
				<div class="clear"/>
				</div>
				<hr class="hr"/><br/>
				<p class="copy">&copy; Copyright 2015. All Rights Reserved. Privacy Policy</p>
		</footer>
	<script src="http://code.jquery.com/jquery-2.1.0.min.js"></script>
	<script src="js/myscripts.js"></script>
	</body>
</html>